apply plugin: 'com.android.application'

android {
    namespace 'org.miniarino.desktop'
    compileSdk 34
    ndkVersion '29.0.14206865'

    defaultConfig {
        applicationId 'org.miniarino.desktop'
        minSdkVersion 24
        targetSdkVersion 34
        versionCode 2
        versionName '0.2.0-xfce-spike'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(':lorie')
}
